name: twelfth_power_of_two
description: 新しいFlutterプロジェクト。
# 以下の行は、`flutter pub publish`を使用してパッケージが誤ってpub.devに公開されるのを防ぎます。
# プライベートパッケージに推奨されます。
publish_to: 'none' # pub.devに公開する場合はこの行を削除します。

# 以下は、アプリケーションのバージョンとビルド番号を定義します。
# バージョン番号は1.2.43のように3つの数字で構成されており、必要に応じてビルド番号が続きます。
# バージョンとビルド番号は、それぞれ--build-nameと--build-numberを指定することでflutterビルド時に上書きできます。
# Androidでは、build-nameがversionNameとして、build-numberがversionCodeとして使用されます。
# Androidのバージョニングについての詳細はhttps://developer.android.com/studio/publish/versioningを参照してください。
# iOSでは、build-nameがCFBundleShortVersionStringとして、build-numberがCFBundleVersionとして使用されます。
# iOSのバージョニングについての詳細は
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.htmlを参照してください。
# Windowsでは、build-nameが製品とファイルのバージョンのメジャー、マイナー、パッチ部分として使用され、
# build-numberがビルドサフィックスとして使用されます。
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

# 依存関係は、パッケージが動作するために必要な他のパッケージを指定します。
# パッケージの依存関係を最新のバージョンに自動的にアップグレードするには、
# `flutter pub upgrade --major-versions`を実行してみてください。または、
# 依存関係は、以下のバージョン番号をpub.devで利用可能な最新バージョンに手動で更新することもできます。
# どの依存関係が新しいバージョンを利用できるかを確認するには、`flutter pub outdated`を実行してください。
dependencies:
  flutter:
    sdk: flutter

  # 以下は、Cupertino Iconsフォントをアプリケーションに追加します。
  # iOSスタイルのアイコンにはCupertinoIconsクラスを使用します。
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 下の"flutter_lints"パッケージには、良いコーディング慣習を促進するための推奨lintセットが含まれています。
  # パッケージが提供するlintセットは、パッケージのルートにある`analysis_options.yaml`ファイルで有効にされています。
  # そのファイルには、特定のlintルールを無効にする方法や追加のルールを有効にする方法についての情報があります。
  flutter_lints: ^2.0.0

# このファイルの一般的なDart部分に関する情報は、以下のページを参照してください：https://dart.dev/tools/pub/pubspec

# 以下のセクションは、Flutterパッケージに特有のものです。
flutter:

  # 以下の行により、Material Iconsフォントがアプリケーションに含まれることが保証されます。
  # これにより、material Iconsクラスのアイコンを使用できます。
  uses-material-design: true

  # アプリケーションにアセットを追加するには、以下のようなアセットセクションを追加します：
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 画像アセットは、1つ以上の解像度固有の「バリアント」を参照することができます。
  # https://flutter.dev/assets-and-images/#resolution-awareを参照してください。

  # パッケージの依存関係からアセットを追加する方法についての詳細は、
  # https://flutter.dev/assets-and-images/#from-packagesを参照してください。

  # アプリケーションにカスタムフォントを追加するには、以下のフォントセクションを追加します：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #       - weight: 700
  #     styles:
  #       - italic
  #       - regular

  # カスタムフォントの詳細については
  # https://flutter.dev/custom-fonts/#from-packagesを参照してください。

